# Generated by Django 6.0.2 on 2026-07-12 21:17

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Theme = apps.get_model("themes", "Theme")
    for row in Theme.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0003_theme_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
