# Generated by Django 6.0.2 on 2026-07-12 21:17
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0004_auto_20260712_2117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
